DIR: 
  dataset: "/media/data/hao/maize_tassels_counting_uav_dataset"
  exp: "mtc_uav_csrnet_bn_o8_r025_sigma20_crop512_bs16_epoch500"
  snapshot: "./snapshots"
  result: "./results"

DATASET:
  name: "mtc-uav"
  list_train: "/media/data/hao/maize_tassels_counting_uav_dataset/train.txt"
  list_val: "/media/data/hao/maize_tassels_counting_uav_dataset/val.txt"
  crop_size: (512, 512)
  image_scale: 0.00392156862745098
  image_mean: (0.485, 0.456, 0.406)
  image_std: (0.229, 0.224, 0.225)
  sigma: 20
  resize_ratio: 0.25
  img_max_size: 1000
  preload: True
  random_crop: True
  random_flip: True

MODEL:
  encoder: "csrnet_bn"
  decoder: ""
  counter: "density_map_regressor"
  normalizer: "no_normalizer"
  generator: "density_map_generator"
  visualizer: "densitymap_upsampling_visualizer"
  output_stride: 8
  counter_dim: 64
  pretrain: True
  fix_bn: False

TRAIN:
  checkpoint: "model_ckpt.pth.tar"
  loss: "L2Loss"
  loss_reduction: "mean"
  batch_size: 16
  num_epochs: 500
  optimizer: "SGD"
  lr_encoder: 1e-2
  lr_decoder: 1e-2
  encoder_multiplier: 1
  momentum: 0.95
  weight_decay: 5e-4
  milestones: (200, 400)
  num_workers: 0
  disp_iter: 10
  seed: 2020

VAL:
  checkpoint: "model_best.pth.tar"
  evaluate_only: False
  disp_iter: 10
  val_epoch: 10
  visualization: False
  normalization_before_visualization: True