DIR: 
  dataset: "../data/maize_tassels_counting_dataset"
  exp: "mtc_tasselnetv3_seg_dagger_encoder_lrx10_i64o8_r025_sigma80_crop320_bs16_epoch500"
  snapshot: "./snapshots"
  result: "./results"

DATASET:
  name: "mtc"
  list_train: "../data/maize_tassels_counting_dataset/train.txt"
  list_val: "../data/maize_tassels_counting_dataset/test.txt"
  crop_size: (320, 320)
  image_scale: 0.00392156862745098
  image_mean: (0.485, 0.456, 0.406)
  image_std: (0.229, 0.224, 0.225)
  sigma: 80
  resize_ratio: 0.125
  img_max_size: 1000
  padding_constant: 32
  preload: True
  random_crop: True
  random_flip: True

MODEL:
  encoder: "seg2count"
  decoder: "seg2count_decoder"
  counter: "count_unfolding_regressor_segmenter"
  normalizer: "count_seg_normalizer"
  generator: "count_map_generator_v3"
  visualizer: "direct_averaging_visualizer"
  block_size: 64
  output_stride: 8
  counter_dim: 56

TRAIN:
  checkpoint: "model_ckpt.pth.tar"
  loss: "MTLoss"
  batch_size: 16
  num_epochs: 500
  optimizer: "SGD"
  lr_encoder: 0.01
  lr_decoder: 0.01
  encoder_multiplier: 1
  momentum: 0.95
  weight_decay: 5e-4
  milestones: (200, 400)
  num_workers: 0
  disp_iter: 10
  seed: 2020
  generate_mask: False

VAL:
  checkpoint: "model_best.pth.tar"
  disp_iter: 10
  val_epoch: 10
  evaluate_only: True
  visualization: False
  normalization_before_visualization: True