DIR: 
  dataset: "./data/maize_tassels_counting_dataset"
  exp: "mtc_mcnn_bn_o4_r0125_crop256_bs16_epoch500"
  snapshot: "./snapshots"
  result: "./results"

DATASET:
  name: "mtc"
  list_train: "./data/maize_tassels_counting_dataset/train.txt"
  list_val: "./data/maize_tassels_counting_dataset/test.txt"
  crop_size: (256, 256)
  image_scale: 0.00392156862745098
  image_mean: (0.3859, 0.4905, 0.2895)
  image_std: (0.1718, 0.1712, 0.1518)
  sigma: 80
  resize_ratio: 0.125
  img_max_size: 1000
  padding_constant: 32
  gt_downsampling_rate: 8
  random_crop: True
  random_flip: True

MODEL:
  encoder: "mcnn_bn"
  decoder: ""
  counter: "density_map_regressor"
  normalizer: "no_normalizer"
  generator: "density_map_generator"
  visualizer: "densitymap_upsampling_visualizer"
  output_stride: 4
  counter_dim: 30

TRAIN:
  checkpoint: "model_ckpt.pth.tar"
  loss: "L2Loss"
  loss_reduction: "sum"
  batch_size: 16
  num_epochs: 500
  epoch_iters: 5000
  optimizer: "SGD"
  lr_encoder: 1e-6
  lr_decoder: 1e-6
  encoder_multiplier: 1
  momentum: 0.95
  weight_decay: 5e-4
  milestones: (200, 400)
  num_workers: 0
  disp_iter: 10
  seed: 2020

VAL:
  checkpoint: "model_best.pth.tar"
  evaluate_only: False
  disp_iter: 10
  val_epoch: 10
  visualization: False
  normalization_before_visualization: True