DIR: 
  dataset: "/media/data/hao/phenocryst_counting_dataset"
  exp: "pcc_bcnet_i32o32_r0.5_crop2000_400_bs1_epoch500"
  snapshot: "./snapshots"
  result: "./results"

DATASET:
  name: "pcc"
  list_train: "/media/data/hao/phenocryst_counting_dataset/train.txt"
  list_val: "/media/data/hao/phenocryst_counting_dataset/val.txt"
  crop_size: (2000, 400)
  image_scale: 0.00392156862745098
  image_mean: (0.3012, 0.3052, 0.3001)
  image_std: (0.2250, 0.2314, 0.2351)
  sigma: 10
  resize_ratio: 0.5
  img_max_size: 1000
  random_flip: True

MODEL:
  encoder: "bcnet"
  decoder: ""
  counter: "count_interval_classifier"
  normalizer: "no_normalizer"
  generator: "class_map_generator"
  visualizer: "direct_averaging_visualizer"
  output_stride: 32
  block_size: 32
  counter_dim: 512
  num_class: 60
  step_log: 0.1
  start_log: -2
  pretrain: True
  fix_bn: False

TRAIN:
  checkpoint: "model_ckpt.pth.tar"
  loss: "CrossEntropyLoss"
  loss_reduction: "mean"
  batch_size: 1
  num_epochs: 500
  optimizer: "SGD"
  lr_encoder: 1e-3
  lr_decoder: 1e-3
  encoder_multiplier: 10
  momentum: 0.95
  weight_decay: 5e-4
  milestones: (500, 500)
  num_workers: 0
  disp_iter: 10
  seed: 2020

VAL:
  checkpoint: "model_best.pth.tar"
  evaluate_only: False
  disp_iter: 10
  val_epoch: 10
  visualization: False
  normalization_before_visualization: True