DIR: 
  dataset: "./data/rice_seedings_counting_dataset"
  exp: "rsc_tasselnetv2plus_i64o8_r05_crop640_bs16_epoch500"
  snapshot: "./snapshots"
  result: "./results"

DATASET:
  name: "rsc"
  list_train: "./data/rice_seedings_counting_dataset/train.txt"
  list_val: "./data/rice_seedings_counting_dataset/test.txt"
  crop_size: (640, 640)
  image_scale: 0.00392156862745098
  image_mean: (0.4816, 0.5057, 0.3593)
  image_std: (0.0956, 0.0985, 0.0932)
  sigma: 4
  resize_ratio: 0.25
  img_max_size: 1000
  padding_constant: 8
  random_crop: True
  random_flip: True

MODEL:
  encoder: "tasselnetv2plus"
  decoder: ""
  counter: "count_regressor"
  normalizer: "gpu_normalizer"
  generator: "count_map_generator"
  visualizer: "pixel_averaging_visualizer"
  block_size: 64
  output_stride: 8
  counter_dim: 128

TRAIN:
  checkpoint: "model_ckpt.pth.tar"
  loss: "L1Loss"
  batch_size: 16
  num_epochs: 500
  optimizer: "SGD"
  lr_encoder: 0.01
  lr_decoder: 0.01
  encoder_multiplier: 1
  momentum: 0.95
  weight_decay: 5e-4
  milestones: (200, 400)
  num_workers: 0
  disp_iter: 10
  seed: 2020

VAL:
  checkpoint: "model_best.pth.tar"
  evaluate_only: True
  disp_iter: 10
  val_epoch: 10
  visualization: True
  normalization_before_visualization: False