DIR: 
  dataset: "/media/data/hao/shanghaitech_crowd_counting_dataset"
  exp: "sht_a_bcnet_i32o32_r1_bs1_epoch500"
  snapshot: "./snapshots"
  result: "./results"

DATASET:
  name: "sht"
  list_train: "/media/data/hao/shanghaitech_crowd_counting_dataset/part_A_train.txt"
  list_val: "/media/data/hao/shanghaitech_crowd_counting_dataset/part_A_test.txt"
  image_scale: 0.00392156862745098
  image_mean: (0.485, 0.456, 0.406)
  image_std: (0.229, 0.224, 0.225)
  sigma: 10
  resize_ratio: 1.0
  img_max_size: 1000
  random_crop: False
  random_flip: True

MODEL:
  encoder: "bcnet"
  decoder: ""
  counter: "count_interval_classifier"
  normalizer: "no_normalizer"
  generator: "class_map_generator"
  visualizer: "direct_averaging_visualizer"
  output_stride: 32
  block_size: 32
  counter_dim: 512
  num_class: 60
  step_log: 0.1
  start_log: -2
  pretrain: True

TRAIN:
  checkpoint: "model_ckpt.pth.tar"
  loss: "CrossEntropyLoss"
  loss_reduction: "mean"
  batch_size: 1
  num_epochs: 500
  optimizer: "SGD"
  lr_encoder: 1e-3
  lr_decoder: 1e-3
  encoder_multiplier: 1
  momentum: 0.95
  weight_decay: 5e-4
  milestones: (200, 400)
  num_workers: 0
  disp_iter: 10
  seed: 2020

VAL:
  checkpoint: "model_ckpt.pth.tar"
  evaluate_only: False
  disp_iter: 10
  val_epoch: 10
  visualization: False
  normalization_before_visualization: True