DIR: 
  dataset: "../data/shanghaitech_crowd_counting_dataset"
  exp: "shta_tasselnetv2plus_i64o8_r1_crop256_bs16_epoch500"
  snapshot: "./snapshots"
  result: "./results"

DATASET:
  name: "sht"
  list_train: "../data/shanghaitech_crowd_counting_dataset/part_A_train.txt"
  list_val: "../data/shanghaitech_crowd_counting_dataset/part_A_test.txt"
  crop_size: (256, 256)
  image_scale: 0.00392156862745098
  image_mean: (0.4108, 0.3706, 0.0597)
  image_std: (0.2655, 0.2558, 0.2551)
  sigma: 10
  resize_ratio: 1.0
  img_max_size: 1000
  padding_constant: 4
  gt_downsampling_rate: 4
  random_crop: True
  random_flip: True

MODEL:
  encoder: "tasselnetv2plus"
  decoder: ""
  counter: "count_regressor"
  normalizer: "gpu_normalizer"
  generator: "count_map_generator"
  visualizer: "pixel_averaging_visualizer"
  block_size: 64
  output_stride: 8

TRAIN:
  checkpoint: "model_ckpt.pth.tar"
  loss: "L1Loss"
  loss_reduction: "mean"
  batch_size: 16
  num_epochs: 500
  optimizer: "SGD"
  lr_encoder: 1e-2
  lr_decoder: 1e-2
  encoder_multiplier: 1
  momentum: 0.95
  weight_decay: 5e-4
  milestones: (200, 400)
  num_workers: 0
  disp_iter: 10
  seed: 2020

VAL:
  checkpoint: "model_best.pth.tar"
  evaluate_only: False
  disp_iter: 10
  val_epoch: 10
  visualization: False
  normalization_before_visualization: True